// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGA9nP9ffIcFanNvPT0Yrqgtev8F9LYxk',
    appId: '1:148311348934:web:663cf951ba1cc8275f69c7',
    messagingSenderId: '148311348934',
    projectId: 'recroot-66242',
    authDomain: 'recroot-66242.firebaseapp.com',
    storageBucket: 'recroot-66242.firebasestorage.app',
    measurementId: 'G-9W7YV6WW1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbeB2K7n4FSl0_-aPPkG9RZQwaDJ0Iitw',
    appId: '1:148311348934:android:8f91138993a9029a5f69c7',
    messagingSenderId: '148311348934',
    projectId: 'recroot-66242',
    storageBucket: 'recroot-66242.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2EdbC6QgoM_E_Qczm3-kS5tswQeyftoQ',
    appId: '1:148311348934:ios:8d6ec80b284cd6a05f69c7',
    messagingSenderId: '148311348934',
    projectId: 'recroot-66242',
    storageBucket: 'recroot-66242.firebasestorage.app',
    iosBundleId: 'com.example.recroot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2EdbC6QgoM_E_Qczm3-kS5tswQeyftoQ',
    appId: '1:148311348934:ios:8d6ec80b284cd6a05f69c7',
    messagingSenderId: '148311348934',
    projectId: 'recroot-66242',
    storageBucket: 'recroot-66242.firebasestorage.app',
    iosBundleId: 'com.example.recroot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGA9nP9ffIcFanNvPT0Yrqgtev8F9LYxk',
    appId: '1:148311348934:web:f5b9bc3ac7a58cde5f69c7',
    messagingSenderId: '148311348934',
    projectId: 'recroot-66242',
    authDomain: 'recroot-66242.firebaseapp.com',
    storageBucket: 'recroot-66242.firebasestorage.app',
    measurementId: 'G-N7H99BJW45',
  );
}
